# Generated by Django 4.1.1 on 2022-09-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='person',
        ),
    ]
