# Generated by Django 4.1.1 on 2022-09-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_human_desc_human_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Human',
        ),
    ]
